config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  # Defines the root path route ("/")
  root "home#index"

  post '/events/:id', to: 'home#create_event', as: 'create_event'

  get '/events', to: 'home#events', as: 'events'
  get '/emails', to: 'home#emails', as: 'emails'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event
  include ActiveModel::Model
  include ActiveModel::Attributes
  attribute :id,          :string
  attribute :name,        :string
  attribute :description, :string
  attribute :notify,      :boolean, default: false

  alias :notify? :notify
end

app/models/events.rb
#-- encoding: UTF-8
# This class is used for collection of events as these are limited in this scenario.
class Events
  @events = {}

  # returns events with id as key and object as value.
  def self.all
    @events
  end
  
  def self.add(event)
    @events[event.id] = event
  end

  # get a particular event by event id.
  def self.get(event_id)
    @events[event_id]
  end
  
  add(Event.new(id: 'ea01', name: 'Event A', description: 'This is Event A'))
  add(Event.new(id: 'eb02', name: 'Event B', description: 'This is Event B', notify: true))
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # added extra column `name` for devise User model. permitting the same attribute.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # welcome message

  def index
    @response = Iterable::Event.hello
  end

  # create event action: which uses Iterable module which in turn calls mock api and returns responses.

  def create_event
    event = Events.get(params[:id])
    response = Iterable::Event.create_event(current_user.id, event.name, event.id)

    if response['success'] && event.notify?
      # TODO: sent to background job async in case of high volume.
      options = {
        user_id: current_user.id,
        recipient_email: current_user.email,
        campaign_id: 100,
        data_fields: {},
      }
      Iterable::Email.notify(options)
    end

    if response['success']
      msg = "Successfully created event for #{current_user.name}."
    else
      msg = "Event already exists for this user."
    end

    flash[:notice] = msg
    redirect_to root_path
  end

  # listing events from mock api

  def events
    @events = Iterable::Event.list_events
  end

  # listing emails sent from mock api

  def emails
    @emails = Iterable::Email.list_sent_emails
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/emails.html.erb
<h2>Emails</h2>
<hr>
<table>
  <thead>
    <th>userId</th>
    <th>emailAddress</th>
    <th>Content</th>
    <th>Sent At</th>
  </thead>
  <tbody>
    <% @emails.each do |email| %>
      <tr>
        <td><%= email['userId'] %></td>
        <td><%= email['emailAddress'] %></td>
        <td><%= email['body'] %></td>
        <td><%= Time.at(email['timestamp']) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/events.html.erb
<h2>Events</h2>
<hr>
<table>
  <thead>
    <th>Id</th>
    <th>Name</th>
    <th>User Id</th>
    <th>Campaign Id</th>
    <th>Created At</th>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event['eventId'] %></td>
        <td><%= event['eventName'] %></td>
        <td><%= event['userId'] %></td>
        <td><%= event['campaignId'] %></td>
        <td><%= Time.at(event['createdAt']) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h2>Home</h2>
<hr>

<p><%= @response %></p>

<% Events.all.each do |event_id, event| %>
  <%= button_to "Create #{event.name}", create_event_path(event_id), :method => :post, :title => "Create #{event.name}" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Events', events_path %>
        <%= link_to 'Emails', emails_path %>
      </nav>
    </header>

    <main>
      <div>
        <% if current_user %>
          <span style="float: left">Hello <%= link_to current_user.name, 'users/edit' %></span>
          <%= button_to '<i class="gg-log-off"></i>'.html_safe, destroy_user_session_path, :method => :delete, :title => "Logout #{current_user.name}", :style => 'float: right' %>
        <% end %>
      </div>

      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% else %>
        <p class="empty-space"></p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>